POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3NTczZGY5ZWQ4YTM3OWFkZThhNmVlNSIsImlhdCI6MTczNDExNzE2NiwiZXhwIjoxNzM0MTIwNzY2fQ.dwM9qwzALnMz8cVf-5-XRzTrYBJLE-3s4Jj_1NtTxNU

{
    "title": "Tesla Cortex",
    "author": "Mental Speeder",
    "url": "http://moapyr.com/su/tesla_cortex",
    "likes": 11399
}